version: 2

submodules:
  include:
    - freekill-core

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

  apt_packages:
    - openjdk-21-jre
    - graphviz
    - fonts-noto-cjk

  jobs:
    pre_create_environment:
      - bash ./ci-install-plantuml.sh
      - echo $PATH

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
