@startuml
hide empty members

abstract class ClientPlayerBase
abstract class ClientRoomBase
abstract class "Xiangqi.Player" as MyPlayer
abstract class "Xiangqi.RoomBase" as MyRoomBase
class "Xiangqi.ClientPlayer" as MyClientPlayer #pink
class "Xiangqi.Client" as MyClient #pink

MyPlayer <|-d[thickness=2]- MyClientPlayer
MyRoomBase <|-d[thickness=2]- MyClient

MyClientPlayer -u-|> ClientPlayerBase 
MyClient -u-|> ClientRoomBase 

MyClientPlayer -r-* MyClient: 1 .. n
'MyPlayer .r.* MyRoomBase

ClientPlayerBase -l[hidden]- MyPlayer
ClientRoomBase -r[hidden]- MyRoomBase

@enduml

