@startuml
!theme plain
hide empty description
state "等待事件 - C++" as Cpp
Cpp : 由io_context::run()产生的事件循环
Cpp : 主要工作就是等待事件产生
Cpp : 根据事件类型（答复或要求）交给Lua处理

state "处理请求 - Lua" as Req
Req : 处理与游戏流程没有直接关联
Req : 并且与C++底层更是完全无关的事件
Req : 例如预亮技能、投降、旁观等
Req : 一般来说很快就能完成处理
state "游戏逻辑 - Lua" as Game
Game : 处理游戏逻辑
Game : 一般来说会频繁中断

[*] -r-> Cpp : asio::io_context::run()
Cpp -[#blue]-> Req : L->call(HandleRequest)
Req -r[#gray]-> Game : 创建房间、投降之类的特殊事件\n会直接进入游戏逻辑状态
Cpp -[#blue]-> Game : L->call(ResumeRoom)
Game -[#red]-> Cpp : 协程挂起或结束
Req -[#red]-> Cpp : 调用已返回
Cpp -r-> [*] : 若线程生命周期已结束，则终止
@enduml
