@startuml
!theme plain

hide empty description

[*] --> 选中杀: -1
[*] --> 选中丈八蛇矛: 0
[*] --> 选中苦肉: 1
选中杀 --> 杀选中孙权: 5
选中杀 --> 杀选中华佗: -5
选中丈八蛇矛 --> 丈八选中杀: -1
选中丈八蛇矛 --> 丈八选中闪: -1
丈八选中杀 --> 丈八选中杀和闪: -1
丈八选中闪 --> 丈八选中杀和闪: -1
丈八选中杀和闪 --> 丈八杀闪选择孙权: 5
丈八选中杀和闪 --> 丈八杀闪选择华佗: -5

@enduml
